{
  "hash": "3762b8f1a3bf117e30ef36fa1292c539",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Stratified Analysis\"\nsubtitle: \"Carehome Outbreak Exercise\"\n---\n\n\n\n## Set yourself up\n\nOne more time, start with the backup data `carehome_clean2.rds`. Start a new script or continue working on the previous one, but ideally start a new one. The libraries are the same than the previous exercise:\n\n``` r\n## Check wether pacman is installed and activate it or install and activate otherwise\nif(!require(\"pacman\")){install.packages(pacman)}\n\n## Activate libraries with pacman\npacman::p_load(\n  here,          # to create file paths\n  rio,           # to import data\n  janitor,       # tools for data cleaning and exploration\n  gtsummary,     # for summary tables\n  skimr,         # to explore dataframes  [NEW ONE]\n  EpiStats,      # for univariate epidemiological analyses\n  epitools,      # for performing risk ratio estimation\n  tidyverse,     # for data manipulation (always the last library!!!)\n  \n  update = T     # to make sure libraries are updated if new versions exist\n)\n\n## Import clean data using rio and here\nclean <- import(here(\"data\", \"backup\", \"carehome_clean2.rds\"), trust = T)\n```\n\n## 1. Consider Confounding and Effect Modification\n\nOnce you have identified food items associated with an elevated risk of becoming a case, the next step is to whether those associations are distorted or modified by a third variable.\n\nConfounding and effect modification are **two distinct phenomena**, both involving a third variable, but leading to very different interpretation:\n\n- **Confounding** is a **distortion** of the observed association. The third variable is associated with both both the exposure and the outcome, and the crude estimate does not reflect the true effect (bias). When we stratify by the confounder, the stratum-specific estimates are similar to each other but differ from the crude estimate. We adjust for the confounding variable to control it.\n\n- **Effect modification** (aka **interaction**) is a real phenomenon: the effect of the exposure on the outcome genuinely differs across levels of the third variable. When we stratify, the stratum-specific estimates differ meaningfully from each other. Effect modification is not corrected because it is not a bias, it is described and reported openly.\n\nWe investigate both through stratification. For medium-to-large datasets, exploring variable by variable becomes impractical and we turn to regression methods. Here we will use `csinter()` from `EpiStats` to manually explore how the association varies across the levels of a third one.\n\n### Spanish tortilla as exposure of interest\n\nSpanish tortilla came out second in RR during univariable analysis, suggesting a potential association between eating tortilla and becoming a case. A plausible explanation is that people who ate russian salad also ate Spanish tortilla, so the effect of tortilla is a simple reflection of the effect of russian salad (i.e., *confounding*). Alternatively, the tortilla effect could genuinely differ depending on whether russian salad was eaten (i.e., *effect modification*).\n\nStratification lets us distinguish between the two. The question is: *does the association between Spanish tortilla and becoming a case hold once we account for the russian salad consumption?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Stratified analysis between tortilla and becoming a case, by Russian salad consumption\ncsinter(x = clean, \n        cases = \"case\", \n        exposure = \"spanish_tortilla\", \n        by = \"russian_salad\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$df1\n  CSInter case - spanish_tortilla by(russian_salad) Total Cases Risk %\n1                                 russian_salad = 1    81  <NA>     NA\n2                                           Exposed    53    30  56.60\n3                                         Unexposed    28    10  35.71\n4                                                      NA  <NA>     NA\n5                                 russian_salad = 0    80  <NA>     NA\n6                                           Exposed    26     3  11.54\n7                                         Unexposed    54     6  11.11\n8                                                      NA  <NA>     NA\n9                               Missing / Missing %     0  0.0%     NA\n           P.est. Stats 95%CI.ll 95%CI.ul\n1 Risk difference  0.21    -0.01     0.43\n2      Risk Ratio  1.58     0.91     2.75\n3 Attrib.risk.exp  0.37    -0.09     0.64\n4 Attrib.risk.pop  0.28       NA       NA\n5 Risk difference  0.00    -0.14     0.15\n6      Risk Ratio  1.04     0.28     3.83\n7 Attrib.risk.exp  0.04    -2.55     0.74\n8 Attrib.risk.pop  0.01       NA       NA\n9            <NA>    NA       NA       NA\n\n$df2\n                                     Point Estimate Chi2 p.value  Stats\n1                         Woolf test of homogeneity 0.34   0.558     NA\n2                     Crude RR for spanish_tortilla   NA      NA   2.14\n3 MH RR spanish_tortilla adjusted for russian_salad   NA      NA   1.46\n4                    Adjusted/crude relative change   NA      NA -31.83\n  95%CI.ll 95%CI.ul\n1       NA       NA\n2     1.28     3.57\n3     0.88     2.43\n4       NA       NA\n```\n\n\n:::\n:::\n\n\nWhen reading the output, compare:\n\n- The **stratum-specific RRs** to each other: if they differ meaningfully, suspect effect modification\n\n- The **crude RR to the Mantel-Haenszel adjusted RR**: if they differ substantially (rule of thumb for difference: \\> 10-20%) and the strata are homogeneous, suspect confounding.\n\n**Action** — Is the relationship between Spanish tortilla and becoming a case confounded by the consumption of Russian salad?\n\n::: {.callout-caution collapse=\"true\" appearance=\"minimal\" icon=\"false\"}\n## See the solution\n\n**Step 1 — Any effect modification?** Compare the two stratum-specific RRs:\n\n- Russian salad = 1 → RR = 1.58 (95% CI 0.91–2.75)\n- Russian salad = 0 → RR = 1.04 (95% CI 0.28–3.83)\n\n**Step 2 — Any confounding?** Compare the crude and the adjusted RR:\n\n- Crude RR = 2.14 (95% CI 1.28–3.57)\n- MH-adjusted RR = 1.46 (95% CI 0.88–2.43)\n- Relative change = –31.83 %\n\nA relative change above \\~10–20 % is a common rule of thumb for meaningful confounding, and here it is roughly 32 %. The adjusted CI also crosses 1. So the apparent association between Spanish tortilla and becoming a case is **largely explained by Russian salad consumption**: once we account for who ate salad, tortilla no longer shows a clear independent effect.\n:::\n\n**Action** — Check whether an association exists between eating Russian salad and Spanish tortilla. What implication does it have for assessing confounding or effect modification? Tip: you learned about the appropriate test a moment ago.\n\n::: {.callout-caution collapse=\"true\" appearance=\"minimal\" icon=\"false\"}\n## See the solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Chi-square test of association between two binary variables\nchisq.test(clean$spanish_tortilla, clean$russian_salad)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  clean$spanish_tortilla and clean$russian_salad\nX-squared = 16.173, df = 1, p-value = 5.78e-05\n```\n\n\n:::\n:::\n\n\nThe Chi-squared test clearly identifies a correlation between the two food items, with a p-value of 5.78e-05 (0.0000578)\n\n**Why does this matter, and what should we see?** For a variable to act as a **confounder**, it must satisfy three conditions:\n\n1.  Be associated with the **exposure** (here, Spanish tortilla).\n2.  Be associated with the **outcome** (here, becoming a case), independently of the exposure.\n3.  Not be on the causal pathway between exposure and outcome.\n\nThis check addresses the condition 1. We know condition 2 from the univariable analysis, and condition 3 is plausible. If people who ate Russian salad were also much more likely to eat Spanish tortilla, then part of the crude \"tortilla effect\" we saw earlier was really the Russian salad effect leaking through — which is exactly the pattern of confounding we observed when the adjusted RR dropped from 2.14 to 1.46.\n:::\n\n### Optional: explore russian salad as the exposure of interest\n\n**Action** — Conversely, is the association between Russian salad and becoming a case confounded by the consumption of Spanish tortilla? Discuss the result.\n\n::: {.callout-caution collapse=\"true\" appearance=\"minimal\" icon=\"false\"}\n## See the solution\n\n**Step 1 — Any effect modification?** Compare the two stratum-specific RRs for Russian salad:\n\n- Spanish tortilla = 1 → RR = 4.91 (95% CI 1.65–14.59)\n- Spanish tortilla = 0 → RR = 3.21 (95% CI 1.30–7.93)\n\nWoolf's test gives p = 0.558, so there is no statistical evidence that the two RRs differ. Both are also well above 1 with CIs that exclude the null: the Russian salad effect is present and strong regardless of tortilla consumption.\n\n**Step 2 — Any confounding?**\n\n- Crude RR = 4.39 (95% CI 2.28–8.44)\n- MH-adjusted RR = 4.05 (95% CI 1.97–8.32)\n- Relative change = –7.68 %\n\nThe adjusted estimate is almost identical to the crude one (change well below the \\~10 % rule of thumb), and the CI remains far from 1. **Spanish tortilla does not confound the Russian salad – case association.**\n\n**Step 3 — Put the two stratified analyses side by side**\n\n|   | Tortilla as exposure | Russian salad as exposure |\n|----|---:|---:|\n| Crude RR | 2.14 (1.28–3.57) | 4.39 (2.28–8.44) |\n| MH-adjusted RR | 1.46 (0.88–2.43) | 4.05 (1.97–8.32) |\n| Relative change (adj vs crude) | –31.8 % | –7.7 % |\n| Adjusted CI crosses 1? | Yes | No |\n\nThis **asymmetry** is the key diagnostic result of the stratified analysis:\n\n- The crude tortilla effect **collapses** when we account for Russian salad consumption → the association was largely explained by the fact that tortilla-eaters also tended to eat Russian salad.\n- The crude Russian salad effect **persists almost unchanged** when we account for tortilla consumption → Russian salad is associated with disease independently of tortilla.\n\nTaken together, the evidence points to **Russian salad as the likely vehicle of the outbreak**, with Spanish tortilla acting as a \"passenger\" exposure whose apparent effect was confounded by salad consumption.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}